### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by tonyxiao** [epsagon/epsagon-node#100]
This is something I'm using internally in our TypeScript project. It'd be great if epsagon included `index.d.ts` inside of itself. 

```ts
// epsagon.d.ts
declare module 'epsagon' {
  import 'aws-lambda'

  export function init(options: {
    token: string
    appName: string
    metadataOnly?: boolean
  }): void
  export function label(key: string, value: string): void
  export function setError(error: Error): void

  type Wrapper<T extends AWSLambda.Handler> = (f: T) => T

  export function lambdaWrapper<T extends AWSLambda.Handler>(f: T): T
  export function stepLambdaWrapper<T extends AWSLambda.Handler>(f: T): T
  export function nodeWrapper<T extends Function>(f: T): T
  export function wrapBatchJob<T extends Function>(f: T): T
}

```

**Comment by yandy-r** [comment]
>  This issue has been resolved in version 1.23.1 
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/epsagon)
> * [GitHub release](https://github.com/epsagon/epsagon-node/releases/tag/v1.23.1)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot

I know this was supposed to be fixed, but when I `npm i epsagon` and include in typescript project,  the error of **cannot find definitions file** still shows up on 1.31.7, even install 1.23.1 is the same. I see the index.d.ts in the src folder here, but somehow that's not making it to NPM during packaging. as the only thing making it inside the `node_modules` folder is a bundle.js file.

I had to manually create an `epsagon.d.ts` file and put it somewhere in my project structure to make the error go away.

**Comment by ranrib** [comment]
Hi @IPyandy, we would love to fix that. Do you have any idea how to do that? Otherwise, you can also open a PR if you got a fix.

**Comment by yandy-r** [comment]
Hi @ranrib, I created a PR #153 that should fix this, depending on how the **semantic-release** utility is configured as I'm not familiar with it.

I linked a dependency to the local working version in a project I'm working and types now work correctly.

**Comment by ranrib** [comment]
Hi @IPyandy, you can find the new version under the PR to master - https://github.com/epsagon/epsagon-node/pull/154 (1.32.1)
Many thanks for your contribution!!
