### ISSUE TITLE
Support for ALB?

### ISSUE THREAD

**Issue by akum32** [epsagon/epsagon-node#125]
Hi,

Often it can be optimal to use an AWS Application Load Balancer instead of API Gateway. Does Epsagon track ALBs? 

The docs don't mention this but just wanted to confirm: https://docs.epsagon.com/docs/nodejs

Thanks.

**Comment by ranrib** [comment]
Hi there, currently you will see the payload in Epsagon but the icon will be presented as an API Gateway. We will take care to fix that :)

**Comment by ranrib** [comment]
I don't see however any traces/invocations from you - can you get in touch with our support through the product?
