### ISSUE TITLE
Question: Epsagon Lambda Wrapper. How to create errors responses?

### ISSUE THREAD

**Issue by belezebu** [epsagon/epsagon-node#148]
Hello guys.

I have a question related with Epsagon lambda wrapper. When I wrap a lambda I'm loosing the possibility to correctly handle the error and create the correct error response at the moment. What is the best solution for this problem?

E.g.: I want to be able to throw a custom error such as NotFound('product x not found') and create the appropriate APIGateway response: 

```
 statusCode: 404 
 message: product x not found
```

Thank you

**Comment by ranrib** [comment]
Hi @belezebu - when you wrap your Lambda with Epsagon we do not change the return value. we also propagate any exceptions that happen in the code (we don't mask them).
In general, in Lambda functions, you can't both throw an exception, and send a custom code.
In your case, I think that you're looking for to do something like:
```
if (someErrorHappened) {
  epsagon.setError(NotFound('product x not found'))
}

return {
 statusCode: 404 
 message: product x not found
}

```

Which will result in getting alert on Epsagon, and return the right value to API Gateway

**Comment by belezebu** [comment]
Hello @ranrib. Thanks for the explanation!
