### ISSUE TITLE
Use TransactionId for tracing in OpenWhisk

### ISSUE THREAD

**Issue by chetanmeh** [epsagon/epsagon-node#163]
Currently tracing using `__ACTIVATION_ID` as id for tracing in OpenWhisk which works well for seeing calls made from withing single activation. 

Recently in OpenWhisk we also enabled exposing the transactionId (apache/openwhisk#4585) i.e. `__TRANSACTION_ID` which may be better suited as tracing id (in place of activationId) as it enables tracing requests made within a sequence or composition also. 

The transactionId is also exposed as `X-Request-Id` and hence exposed to end users (apache/openwhisk#3199).

Further note that support for this feature is new. So the library may want to have a fallback to activationId if transactionId is not present

**Comment by ranrib** [comment]
Hi @chetanmeh! Today we use the activation ID to connect between action that invokes another action. We will collect the transaction ID as well, but in order to use it to connect to other events we might need a bit more information around the flow - can you share any relevant scenario please?

**Comment by liadgo** [comment]
Hey @chetanmeh,
A new version has been released ([1.36.0](https://github.com/epsagon/epsagon-node/releases/tag/v1.36.0)) and it now supports collecting `__TRANSACTION_ID` in OpenWhisk.

**Comment by chetanmeh** [comment]
Thanks @LiadGoren . I believe it was done via #175
