### ISSUE TITLE
http.get(url, options) not supported

### ISSUE THREAD

**Issue by trieloff** [epsagon/epsagon-node#165]
The `get` function of the NodeJS `http` module can be called with `options` or with `url, [options]. The wrapper was built only for the `options` case, and assumes that the first argument is always an object, when it can be an object, a string, or a `URL` object.

When `http.get` is used with a URL as in https://github.com/adobe/helix-resolve-git-ref/blob/233400fb22d69c79153d7ff126d8ca85c0210ce2/src/index.js#L44 it results in traces to HTTP requests being recorded as pointing to `http://localhost/`. This is due to the assumption that `options` will always be an object here: https://github.com/epsagon/epsagon-node/blob/b9ab8dd8043087a34abe2bcd0c69a669ea6fe51b/src/events/http.js#L90-L95

**Comment by henperez** [comment]
Hi @trieloff , This issue is now fixed in #168
