### ISSUE TITLE
Provide option to see queries when sending requests to BigQuery

### ISSUE THREAD

**Issue by MarquiseRosier** [epsagon/epsagon-node#178]
it'd be pretty cool if we can see the query being sent to bigquery in the tags!

**Comment by trieloff** [comment]
Ideally it would work similar to the PG wrapper: https://github.com/epsagon/epsagon-node/blob/master/src/events/pg.js

**Comment by ranrib** [comment]
Added in https://github.com/epsagon/epsagon-node/issues/178
