### ISSUE TITLE
Use with Step Function

### ISSUE THREAD

**Issue by rob3000** [epsagon/epsagon-node#201]
Hi I've been using epsagon with AWS lambda's but wanted to know how to get tracing working with step functions triggered by a cloudwatch schedule. Based on the examples you can:

```
module.exports.hello = epsagon.stepLambdaWrapper((event, context, callback) => {
   // Your code is here
});
```
But as my step function is triggered by cloud watch would each step(Lambda) need to be wrapped in the `stepLambdaWrapper` ?

**Comment by ranrib** [comment]
Hi @rob3000 - yes, every function in a step should be wrapped with `stepLambdaWrapper`.
If you have any other issue you are more than welcome to get assistance from our in-product help widget
