### ISSUE TITLE
no traces are sent when JSON.stringify throws

### ISSUE THREAD

**Issue by solaris007** [epsagon/epsagon-node#271]
When sending a trace in `sendCurrentTrace(traceSender)`,  a `traceJson` is assembled and later its size checked by `JSON.stringify`ing it:

```
    if (JSON.stringify(traceJson).length >= consts.MAX_TRACE_SIZE_BYTES) {
        // ...
    }
```

JSON.stringify can throw when the JSON has issues, such as a circular reference:

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.<anonymous> (<anonymous>:1:27)
    at sendCurrentTrace (/code/dist/getAllChannels/index.js:37495:5)
    at Promise.all.then (/code/dist/getAllChannels/index.js:37653:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Probably this error should be caught *and logged* :D and other traces allowed to be sent.

**Comment by ekremney** [comment]
@ranrib @henprtz

**Comment by ranrib** [comment]
Thanks, we're on it!

**Comment by henperez** [comment]
Fixed by reporter

**Comment by solaris007** [comment]
@henprtz please re-open. i did not create this issue because of the underlying circular reference, but because when the JSON.stringify fails for any reason, epsagon just silently dumps the trace. No log, no try catch. Finding out the issue required debugging your code, as the debug level epsagon level log only said "sending trace"

**Comment by henperez** [comment]
@solaris007 - I agree, we'll fix that ASAP.
