### ISSUE TITLE
Access _headers produces DEP0066 warning in Node8 and above

### ISSUE THREAD

**Issue by amurdock** [epsagon/epsagon-node#272]
The implementation in `src/events/http.js` (lines 265-269) references a deprecated property. See https://nodejs.org/dist/latest-v12.x/docs/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames for more information.

**Comment by ranrib** [comment]
Thanks @amurdock, the fixed version should be deployed very soon. Please follow the PR.

**Comment by amurdock** [comment]
@ranrib really appreciate the quick turn around!
