### ISSUE TITLE
Unable to import module 'epsagon_handlers/run-epsagon'

### ISSUE THREAD

**Issue by gangster** [epsagon/epsagon-node#29]
This is probably my fault, but I'm getting this error when I try to wrap a function.    I am using Typescript, so maybe that has something to do with it.    Anyways, I have a lambda in my state machine that looks something like the following:

```typescript
const epsagon = require('epsagon');
epsagon.init({
  token: '...',
  appName: 'Ingestion',
  metadataOnly: false, // Optional, send more trace data
});


let upsertFile: Handler = async (
  event: UpsertFileEvent,
  _: Context,
  callback: Callback,
) => {
 //...
}
upsertFile = epsagon.lambdaWrapper(upsertFile);
export { upsertFile };
```

And I am seeing this error occur in my `run` function, which is responsible for executing the state machine, where `upsertFile` lives.

```
Unable to import module 'epsagon_handlers/run-epsagon': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/epsagon_handlers/run-epsagon.js:3:15)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
```

Any pointers on what I might be doing wrong here?

Thanks!

**Comment by gangster** [comment]
Forgot to mention, I am also using serverless framework and the plugin.

**Comment by ranrib** [comment]
Hi there @gangster !

In case you are using the serverless framework plugin, you don't need to manually add the code and the wrapper - the plugin takes care for it.

To your specific issue - any chance the 'epsagon_handlers' is under the exclude section in your yml file?

If it doesn't help, will you be able to share your serverless.yml file please?

Thanks

**Comment by galbash** [comment]
Hi @gangster ,
We made some updates to the serverless plugin as well as the node library, and the issue should be resolved now. Can you update the plugin and the library to the latest versions and let us know if the issue is fixed? 

Thanks!
