### ISSUE TITLE
Doesn't work with `got`

### ISSUE THREAD

**Issue by brigitte0** [epsagon/epsagon-node#295]
epsagon version: 1.61.5
got version: 11.0.2

Recently added [got](https://github.com/sindresorhus/got) to my project and received the following error when calling `got.get(url, options)` with Epsagon enabled

```
TypeError: i is not a function
      at ClientRequest.patchedCallback (webpack:///../node_modules/epsagon/dist/bundle.js?:1:63790)
      at Object.onceWrapper (events.js:428:26)
      at ClientRequest.emit (events.js:333:22)
      at ClientRequest.EventEmitter.emit (domain.js:485:12)
      at ClientRequest.origin.emit (webpack:///../node_modules/got/node_modules/@szmarczak/http-timer/dist/source/index.js?:39:20)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:602:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
      at TLSSocket.socketOnData (_http_client.js:471:22)
      at TLSSocket.emit (events.js:321:20)
      at TLSSocket.EventEmitter.emit (domain.js:485:12)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:273:9)
      at TLSSocket.Readable.push (_stream_readable.js:214:10)
      at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```

The error is thrown by the following line https://github.com/epsagon/epsagon-node/blob/master/src/events/http.js#L273 because callback is an object and not a function.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/21266728/83499188-87296f00-a4ef-11ea-9290-603839c90513.png">

**Comment by succulentpup** [comment]
I'm still facing this error on epsagon 1.81.2.
Node 10.x
"serverless-webpack": "^5.3.3"
"terser-webpack-plugin": "^4.1.0"
"webpack": "^4.44.1" 
"epsagon": "^1.82.0"
 "got": "^11.6.0", (with got 9.0.6, there is no issue)

Ref ticket in stackoverflow: https://stackoverflow.com/questions/63742723/typeerror-i-is-not-a-function-aws-lambda-wrapped-with-epsagon

Following is the error snippet from cloudWatch.
```
{
  "errorType": "TypeError",
  "errorMessage": "i is not a function",
  "stack": [
    "TypeError: i is not a function",
    "    at ClientRequest.patchedCallback (/opt/nodejs/node_modules/epsagon/dist/bundle.js:1:60626)",
    "    at Object.onceWrapper (events.js:286:20)",
    "    at ClientRequest.emit (events.js:203:15)",
    "    at ClientRequest.EventEmitter.emit (domain.js:448:20)",
    "    at ClientRequest.e.emit.f [as emit] (/var/task/epsagon_handlers/abcdNameChanged-epsagon.js:2:1080726)",
    "    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)",
    "    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)",
    "    at TLSSocket.socketOnData (_http_client.js:451:20)",
    "    at TLSSocket.emit (events.js:198:13)",
    "    at TLSSocket.EventEmitter.emit (domain.js:448:20)"
  ]
}
```

**Comment by ranrib** [comment]
Hi @succulentpup - thanks for sharing.
The error seems weird, because it misses the exact fix that was done, with verifying that i is a function.
It seems that you're using the layer version of Epsagon (since the path is `/opt/nodejs/node_modules/`) - My assumption is that it's either not the latest version, or that accidentally the layer is still there.
Can you verify please, and share the full layer ARN?

**Comment by succulentpup** [comment]
@ranrib Thanks a ton for your response.
Your hint on layers helped me a lot. Actually when epsagon auto-tracing is enabled on any lambda, it adds a layer called 

> epsagon-node-layer

to that lambda.
It shows only in lambda configuration when we go thru aws console. If we use 'aws lambda list-layers'  the response does not show this layer 'epsagon-node-layer' details.
Finally, I've disabled epsagon auto-tracing and the error is gone.
I think that the layer is added by epsagon to that lambda. If so, can epsagon update that layer to have the fix installed?
Layer ARN: arn:aws:lambda:eu-west-1:ACCOUNTNUMBER:layer:epsagon-node-layer:177
