### ISSUE TITLE
Dependency Renders Node.JS<v12 Unsupported

### ISSUE THREAD

**Issue by haddadnj** [epsagon/epsagon-node#315]
`uuid-to-hex` version `1.1.1` no longer supports node versions under 12.

https://github.com/DeRain/uuid-to-hex/commit/2b5ccb1df554978c2ba894b9d23eacfeedb4faf6

https://github.com/epsagon/epsagon-node/blob/master/package.json#L92

Proposing updating dependency declaration to `"uuid-to-hex": "~1.0.3",`

**Comment by ranrib** [comment]
Thanks @haddadnj - we're on it
