### ISSUE TITLE
kafkajs wrapper changes behaviour of the original library

### ISSUE THREAD

**Issue by danielbatica** [epsagon/epsagon-node#382]
Kafka eachMessage wrapper does not return the promise. This leads to the eachMessage not being awaited. Event processing in the consumer is no longer sequential when async tasks are executed inside.

[This call](https://github.com/epsagon/epsagon-node-frameworks/blob/37f58a67cf10a47e98e9323b8d55f63c08997a02/src/wrappers/kafkajs.js#L67) should be awaited or the result of the call (the promise) should be returned to kafkajs.

cc: @ekremney

**Comment by ekremney** [comment]
This issue causes our pods to fail due to OOM. Could you please take a look at it. @danielbatica has already a solution for it.

cc: @ranrib @henprtz

**Comment by danielbatica** [comment]
Proposed fix here: https://github.com/epsagon/epsagon-node-frameworks/pull/77/files

**Comment by ranrib** [comment]
Released in version `1.23.3`. Thanks @danielbatica!
