### ISSUE TITLE
AWS Batch wrapper cannot execute function

### ISSUE THREAD

**Issue by ymwjbxxq** [epsagon/epsagon-node#433]
Your documentation report this
https://docs.epsagon.com/docs/nodejs-aws-batch

I am using TypeScript and I have tried multiple things but I am getting always the same error.

**try number 1:**
`export const startExecution: any = epsagon.wrapBatchJob(doit);

function doit() {
  console.log("sfsdffdsf")
}`

ERROR:
 TypeError: handler_1.startExecution is not a function

**try number 2:**
`export const startExecution: any = epsagon.wrapBatchJob((): any => {
  console.log("sfsdffdsf")
});`

ERROR:
 TypeError: handler_1.startExecution is not a function

**try number 3:**
`export const startExecution: any = epsagon.wrapBatchJob(async (): Promise<any> => {
  await runBatch();
});

export const runBatch = async (): Promise<any> => {
    // code here
};`

ERROR:
 TypeError: handler_1.startExecution is not a function

It is interesting to note that the unit tests are all passing if you replace wrapBatchJob with lambdaWrapper and both of them have the same definition:
`
export function lambdaWrapper<T extends Function>(f: T): T

export function wrapBatchJob<T extends Function>(f: T): T
`

Thanks

**Comment by ymwjbxxq** [comment]
Hi Ran,

I am playing around with the code and  with this little change I can run a function but not sure how to see if I broke the aws batch

`module.exports.wrapBatchJob = function wrapBatchJob(functionToWrap) {`

and unit tests are:

`it('wrapBatchJob: call sync function', () => {
        function doit(arg) {
          expect(arg).to.equal("params");
        }
        batchWrapper.wrapBatchJob(() => doit("params"));
    });
  
    it('wrapBatchJob: call async function', async () => {
        async function doit(arg) {
            expect(arg).to.equal("params");
        }
        batchWrapper.wrapBatchJob(async () => await doit("params"));
    });

    it('wrapBatchJob: sanity', () => {
        batchWrapper.wrapBatchJob(this.callbackStub);`

But again not really sure if this is enough or must be returned in the shimmer.wrap function

**Comment by ranrib** [comment]
Hi @ymwjbxxq please look at the updated docs:
```
const epsagon = require('epsagon');
epsagon.init({
  token: 'epsagon-token',
  appName: 'app-name-stage',
  metadataOnly: false,
});

epsagon.wrapBatchJob();


function process(params) {
  // Your code is here
}
```

Thanks for pointing out the issue!

**Comment by ymwjbxxq** [comment]
![Screenshot 2021-02-16 at 15 14 58](https://user-images.githubusercontent.com/78874812/108074683-ca217780-7069-11eb-80e3-96e48226f680.png)

I do not understand how this fix the problem. I think now you need to change the TypeScript Definition

**Comment by ranrib** [comment]
You're right, I've created a PR

**Comment by ymwjbxxq** [comment]
you were faster than me...
