### ISSUE TITLE
AWS AppConfig support

### ISSUE THREAD

**Issue by ymwjbxxq** [epsagon/epsagon-node#447]
Would be nice to add a special icon for AWS AppConfig especially the integration with Lambda function
https://docs.aws.amazon.com/appconfig/latest/userguide/appconfig-integration-lambda-extensions.html

When you integrate AppConfig you will have:

- Lambda layer (arn:aws:lambda:{REGION}:066940009817:layer:AWS-AppConfig-Extension:{version}
- Environment variable (configurable)

| Environment variable  | Default value |
| ------------- | ------------- |
| AWS_APPCONFIG_EXTENSION_POLL_INTERVAL_SECONDS  | 45  |
| AWS_APPCONFIG_EXTENSION_POLL_TIMEOUT_MILLIS  | 3000  |
| AWS_APPCONFIG_EXTENSION_HTTP_PORT  | 2772 |

At the moment is the serviceMap you see it as http calls.

I think you should catch somehow the environment variable or the lambda layer and when there is an http call to "http//locahost:{AWS_APPCONFIG_EXTENSION_HTTP_PORT}/applications/" based on the env variables you do your magic creating the connection (already there but http type)

Lambda example:
`const AWS = require('aws-sdk'); 
const appconfig = new AWS.AppConfig(); 
const http = require('http'); 

exports.handler = async (event) => { 
  const result = await new Promise((resolve, reject) => { 
    http.get("http://localhost:2772/applications/applicationTest/environments/ myTestEnvironment/configurations/myConfigurationProfile", resolve); 
  }); 

  const configData = await new Promise((resolve, reject) => { 
    let data = ''; 
    result.on('data', chunk => data += chunk); 
    result.on('error', err => reject(err)); 
    result.on('end', () => resolve(data)); 
  }); 

  console.log(configData); 
  return JSON.parse(configData); 
}; `

Thanks

**Comment by ymwjbxxq** [comment]
![Screenshot 2021-02-26 at 14 36 45](https://user-images.githubusercontent.com/78874812/109306884-1de94900-7840-11eb-8f53-ff39a014220b.png)

I see the icon has changed and it is great....maybe call it AppConfig would be nice

**Comment by ranrib** [comment]
Thanks @ymwjbxxq! since this call is being captured from the HTTP instrumentation, we would rather leave it as it is to avoid confusion. We can implement in the future tailored support for AppConfig instrumentation.
Other than that - you should not experience any difference functional-wise in the dashboard.
