### ISSUE TITLE
Tracing AWS EventBridge Target Step Functions state machines

### ISSUE THREAD

**Issue by ymwjbxxq** [epsagon/epsagon-node#449]
Hello,

I have a lambda function that add an event into EventBridge to execute a Stepfunction.
Your ServiceMap does not trace this connection.
I can see:

- Lambda to EventBridge (putEvents)
- The first Lambda of the StepFunction completely separated and without the state machine icon as well

This is how I put the event that you trace (putEvents)  
`
const eventRequest: PutEventsRequest = {
      Entries: [{
        EventBusName: process.env.myBus,
        Source: "mySource",
        Detail: JSON.stringify(message),
        DetailType: "myType"
      }]
    };
const response = await this.eventBridge.putEvents(eventRequest).promise();`

Would be nice to have the connection between the services

**Comment by ranrib** [comment]
Added as internal ticket. Thanks!
