### ISSUE TITLE
Node support

### ISSUE THREAD

**Issue by ymwjbxxq** [epsagon/epsagon-node#453]
Hello,

epsagon-node support 8.x, 10.x, 12.x, and 14.x where

8.x has been deprecated since a while
10.x will be deprecated end of April 2021
https://endoflife.date/nodejs

Do you have plans to fork the current version for 8 and 10?

If you do that you will have advantages to keep the "active" version up to date with dependencies, currently because the compatibility to  8.x you cannot update pretty much anything without breaking your CI.

Thanks,
Dan

**Comment by ranrib** [comment]
Hi @ymwjbxxq  - we do plan to deprecate soon Node 8 with the new version 2 of this library. I'm closing this in the meantime
