### ISSUE TITLE
AWS APIGW:  enhanced observability variables

### ISSUE THREAD

**Issue by ymwjbxxq** [epsagon/epsagon-node#457]
Hello,

I can see perfectly in the serviceMap:
APIGW -> LAMBDA

but would be great to enhance the tracing especially on the latency side.
If you follow this link:
https://aws.amazon.com/blogs/compute/troubleshooting-amazon-api-gateway-with-enhanced-observability-variables/

you can break down the latency by:

- WAF
- Authenticate
- Authorizer
- Authorize

and where you are there you can add at least 2 icons:

- WAF
- Cognito

Thanks,
Dan

**Comment by ranrib** [comment]
Thanks @ymwjbxxq! this is unrelated to the node library, and we've forwarded this feature request to our product team 🙏🏻
