### ISSUE TITLE
Tracer no longer supports MongoDB driver V4

### ISSUE THREAD

**Issue by selvendranayyaswamy** [epsagon/epsagon-node#513]
The epsagon tracer no longer supports the tracing of MongoDB calls. I think starting Version 4, MongoDB core dependency has been removed from the MongoDB driver and the entire patching is done based on the MongoDB core module because of which the tracer is not able to find out the wireprotocol folder.

starting from MongoDB version 4, this path is no longer present  'mongodb/lib/core/wireprotocol/index.js'. I have to literally downgrade the mongoDB driver to version 3 to make things to work.

Here is the jist of error
[EPSAGON] patching module: mongodb/lib/core/wireprotocol/index.js
[EPSAGON] found module copies: 0
[EPSAGON] done patching module: mongodb/lib/core/wireprotocol/index.js

**Comment by sagivr2020** [comment]
Hi @selvendranayyaswamy, we added support to MongoDB driver V4.
Please update to the latest version 1.121.2 .
Thanks!
