### ISSUE TITLE
NestJS Support?

### ISSUE THREAD

**Issue by jjosef-rsi** [epsagon/epsagon-node#531]
NestJS uses express (or other supported libraries) under the hood. However, the auto-tracing does not seem to work. Is there a suggested way to get events to register when using NestJS or a similar framework?

**Comment by sagivr2020** [comment]
Hi @jjosef-rsi, it might be supported since it is based on Express.
Please use [epsagon-framework](https://docs.epsagon.com/docs/tracing-libraries/nodejs/nodejs-express/) .

**Comment by sagivr2020** [comment]
@jjosef-rsi I'm closing the issue since it indeed supported by our epsagon-framework library.
