### ISSUE TITLE
AWS-SDK3 split

### ISSUE THREAD

**Issue by ymwjbxxq** [epsagon/epsagon-node#544]
Hello Epsagon Team,

Now that you started supporting the AWS-SDK v3, maybe it is a good idea to split it entirely from the old epsagon-node library.

A few advantages:
- use up to date libraries
- avoid this "Unzipped size must be smaller than 262144000 bytes during the build
- add TypeScript
- add unit tests from scratch

At the moment is all mixed.

Thanks
Dan

**Comment by sagivr2020** [comment]
Hi @ymwjbxxq, we appreciate your suggestions, we'll consider using this approach in order to keep the library organized.
Thanks!
