### ISSUE TITLE
Rust: support

### ISSUE THREAD

**Issue by ymwjbxxq** [epsagon/epsagon-node#546]
Hello Team,

because you are always the first would be nice to support RUST
https://github.com/awslabs/aws-sdk-rust

All the essential serverless services are supported.

It would be nice to know if it is in the roadmap and a rough  ETA just to plan around.

Thanks,
Dan

**Comment by sagivr2020** [comment]
Hi @ymwjbxxq , Thanks for letting us know, at that point, we would like not to implement a new tracing library that we will need to add support in the future.
