### ISSUE TITLE
ECONNREFUSED and timeout when load testing

### ISSUE THREAD

**Issue by ChristopheBougere** [epsagon/epsagon-node#56]
Hi guys!

I'm load testing an API Gateway endpoint. The lambda behind is instrumented with epsagon (I'm using the serverless plugin but I don't think it is related).
I'm sending 2000 requests, one every 10ms.
It works until a point, and then I see a `Error: ECONNREFUSED, Connection refused` and then the handler does not even get called (I don't see any logs, but I can see that the lambda has been invoked). The lambda also timeout, which is weird because I don't see any logs:
![image](https://user-images.githubusercontent.com/1325474/52901233-e41ceb00-3200-11e9-8840-8a94382e0768.png)

I've tried to disable epsagon and the issue does not replicate:
```yaml
epsagon:
  disable: true
```

I kind of expect some lambda not to work, but I would prefer at least to exit so I don't pay until timeout.

Could this be linked to the wrapper?

Best

**Comment by ranrib** [comment]
Hi Christophe!

It's actually a bit weird because we limit the trace sending to 1 second max. In general, when you just run the function separately does it work?
Can you try set EPSAGON_DEBUG=TRUE, and run the load test again please?
If you increase the timeout (let's say 10 seconds) will it stale to that duration?

Thanks!

**Comment by ChristopheBougere** [comment]
Hi Ran,
When I am using the function normally (not load testing), everything works well.

It is the same with 10 seconds timeout:
![image](https://user-images.githubusercontent.com/1325474/52911143-29442a00-32a0-11e9-8101-ccedbe58ee5d.png)

Even with the EPSAGON_DEBUG, I don't see more information:
![image](https://user-images.githubusercontent.com/1325474/52911422-dec4ac80-32a3-11e9-93a1-73f59ea19f21.png)
I see more information when the lambda works though.

I'm struggling replicating the issue. Sometimes the error shows up, but not all the time.
It might also be a Lambda issue (too many containers instanciated), but I find this weird that the lambda timeouts instead of just exitting.

**Comment by ranrib** [comment]
It will be a bit hard to investigate such issue.. Does the ECONNREFUSED come from your code? or from AWS? Can you try and open a ticket to AWS so they'll have a further investigation?

**Comment by ChristopheBougere** [comment]
You're right, it's a bit complicated to investigate like this.
The error does not come from my own code, but it could come from Lambda itself.
I'll reopen if I'm able to find more information.
