### ISSUE TITLE
Epsagon SDK times out with Apollo Federation

### ISSUE THREAD

**Issue by Nicoowr** [epsagon/epsagon-node#560]
We host Apollo Gateway & subservices on AWS Lambda.

Wrapping the gateway with `epsagon.lambdaWrapper` works like a charm.

Wrapping the subservices leads to a time-out though. After some investigation, it seems the graphql query manages to reach the resolver, the resolver runs but never returns. Here is the code I'm using:

```typescript
const handler = epsagon.lambdaWrapper(
    new ApolloServer(
      ...
    ).createHandler<APIGatewayEvent, ProxyResult>({
      expressAppFromMiddleware: addCompressionMiddleware,
      expressGetMiddlewareOptions,
    })
  );

const wrappedHandler: Handler<
    APIGatewayEvent,
    void | APIGatewayProxyResult
  > = async (event, context, callback) => {
    context.callbackWaitsForEmptyEventLoop = false; // tried with & without
    logEvent(event);
    const response = await handler(event, context, callback); // STUCK HERE: adding some logs in the underlying resolver shows it runs but does not return
    logError(response);

    return response;
  };

export { wrappedHandler }
```

`epsagon` version: `1.119.1`
`@apollo/gateway` version: `0.45.1`
`@apollo/subgraph` version: `0.1.5`

**Comment by arbiv** [comment]
Hi,

Epsagon reached its end-of-life. As an alternative, I suggest considering AppDynamics for application monitoring and tracing. I can help connect you with relevant peers or provide additional resources to assist you in your evaluation.
