### ISSUE TITLE
Incompatibility with `stripe-node` library

### ISSUE THREAD

**Issue by guillaumeduboc** [epsagon/epsagon-node#582]
When using the [`stripe-node`](https://www.npmjs.com/package/stripe) library on my project, the call to the api seems to never resolve

I have investigated a little bit and to reproduce the problem you can execute the following lambda

``` javascript
require('http');

export const main = async () => {
  const response = new Promise((resolve, reject) => {
    http.request(
      {
        hostname: 'httpstat.us',
        path: '/200',
        method: 'GET',
      },
      res => {
        resolve(res);
      },
    )
      .on('error', e => {
        reject(e);
      })
      .end();
  });

  const result = await response.then(res => {
    let chunks = '';

    return new Promise((resolve, reject) => {
      res
        .setEncoding('utf-8')
        .on('data', (chunk) => {
          chunks += chunk;
        })
        .on('error', reject)
        .on('end', () => {
          resolve(chunks);
        });
    });
  });

  console.log(result);

  return result;
};
```

If I remove `epsagon` from the project, this lambda works fine.

This code is inspired by the `makeRequest` method of `stripe-node/lib/StripeResource.js`

I will continue investigating the issue but let me know if you have an idea where the problem might be

**Comment by sagivr2020** [comment]
Hi @guillaumeduboc, which stripe-node library version are you using?
We found that versions above 1.169.0 are interferes with async events.

**Comment by guillaumeduboc** [comment]
Hi @sagivr2020, I'm using the version 8.211.0

**Comment by sagivr2020** [comment]
Hi @guillaumeduboc, we've found that from version 1.169.0 the calls interfere with async events (as you mentioned it's not resolved on our end).
We released a new version that handles it, please upgrade to the latest version 1.121.3

**Comment by guillaumeduboc** [comment]
Hi @sagivr2020, I am concerned ignoring the calls to the stripe endpoint makes us lose the information.
Furthermore, if another library uses the `http` module the same way as `stripe` it will raise the same issue.

From what I understand, registering multiple listeners on the data event of the response is responsible for the behaviour.

I have opened a draft PR (#584), solving the problem, to have your point of view
