### ISSUE TITLE
Tracing of calls to latest versions of `stripe-node` is impossible

### ISSUE THREAD

**Issue by guillaumeduboc** [epsagon/epsagon-node#586]
Following #582, I am concerned ignoring the calls to the stripe endpoint makes one lose too much information.
Furthermore, if another library uses the http module the same way as stripe it will raise the same issue.

From what I understand, registering multiple listeners on the data event of the response is responsible for the behaviour.

I have opened #584, solving the problem
Looking forward to your feedback

**Comment by sagivr2020** [comment]
Hi @guillaumeduboc, your PR has been approved by @haddasbronfman.
