### ISSUE TITLE
Epsagon trace split with DynamoDB SDK V3 ?

### ISSUE THREAD

**Issue by Nyugue** [epsagon/epsagon-node#613]
Hi team, 

We just started using Epsagon to monitor our new project build on AWS, with Lambda, DynamoDB and Event Bridge.
We monitor our Lambdas using the SDK and it works well ! (We write code in Typescript fwiw)

We have only one issue : 
A lambda (`firstLambda`) is triggered by an HTTP Event and pushes an item to Dynamo (using SDK V3)
Another lambda (`fanout`) listens to DynamoDB Stream and forwards the event to EventBridge.
The trace of the execution is split in two and in the first Lambda trace, we don't even see the push to Dynamo.

Following [this article that was great](https://dev.to/kumo/monitor-and-debug-your-serverless-applications-painlessly-with-epsagon-258o), I added a custom label `originalRequestId` to try to help getting the trace back together. It is correctly applied and we see it in Epsagon, so we can use it to manually follow our flow execution, but it doesn't help for the trace integrity.

<img width="1631" alt="Capture d’écran 2023-01-12 à 09 34 37" src="https://user-images.githubusercontent.com/80616519/212017480-9f6c7651-ee38-489a-a694-26ea3eef91ec.png">

(lambda and app names were edited)

**Comment by ymwjbxxq** [comment]
Found another issue with ConditionalCheckFailedException. 
Using epsagon.stepLambdaWrapper will somehow overwrite ConditionalCheckFailedException from the SDK, returning undefined but still reporting the trace correctly. Removing epsagon.stepLambdaWrapper will work as expected

```
import { ClientDefaults, DynamoDB } from "@aws-sdk/client-dynamodb";
import { TestQuery } from "./testQuery";
import epsagon from "epsagon";

epsagon.init({
  token: process.env.EPSAGON_TOKEN,
  appName: `test`,
  metadataOnly: false,
});

const clientDefaults: ClientDefaults = {
  region: "eu-central-1",
};
const dynamoClient = new DynamoDB(clientDefaults);

export const handler = epsagon.stepLambdaWrapper(async() => {
  const testQuery = new TestQuery(dynamoClient);
  await testQuery.execute();
  console.log("Done!");

  const response = {
      statusCode: 200,
      body: JSON.stringify('Hello from Lambda!'),
  };
  return response;
});
-------

import { DynamoDB, PutItemCommand, PutItemCommandInput } from "@aws-sdk/client-dynamodb";

export class TestQuery {
    constructor(private readonly dynamoClient: DynamoDB) {}

    public async execute(): Promise<void> {
        const version = "1";
        const putItemParams: PutItemCommandInput = {
            Item: {
                productId: {
                    S: "p-123",
                },
                title: {
                    S: "Some Title",
                },
                version: {
                    S: version,
                },
            },
            ExpressionAttributeValues: {
                ":version": {
                    S: version,
                },
            },
            ConditionExpression: "version <> :version",
            TableName: "product",
        };

        // ACT
        const request1 = new PutItemCommand(putItemParams);
        const request2 = new PutItemCommand(putItemParams);

        await Promise.all(
            [
                this.processQuery(this.dynamoClient, request1),
                this.processQuery(this.dynamoClient, request2),
            ]);
    }

    private async processQuery(dynamoClient: DynamoDB, command: PutItemCommand): Promise<void> {
        try {
            const result = await dynamoClient.send(command);
            console.log("Send command executed!");
            console.log(result);
        }
        catch (error) {
            console.log("Error!");
        if (error.name === "ConditionalCheckFailedException") {
                console.log("ConditionalCheckFailedException");
            }
            else {
                console.log("Other error");
                console.log(error);
            }
        }
    }
}

```
