### ISSUE TITLE
Using lambda layer and tagging inside lambda

### ISSUE THREAD

**Issue by JoaquinFernandez** [epsagon/epsagon-node#617]
Hi!

Since we are deepening our epsagon usage, we have come across a new issue.

To have the best tracing possible on lambdas, we used the lambda layers provided by epsagon, this was originally discussed here, and works like a charm:
https://github.com/epsagon/serverless-plugin-epsagon/issues/121

However, now we want our logger to tag traces based on some parameters given, namely userId.

For this use case, we decided it would make sense to implement it on our logger, since we already tagged some logs, this would make the most sense. That is a package dependency.

When we install the epsagon dependency in this dependency of the main project it is not initialized with the parameters already given to the epsagon layer, this is a problem since we should not initialize it twice:

https://github.com/epsagon/epsagon-node/blob/master/README.md#aws-lambda
> Make sure to choose just one of the methods

How can we proceed here?

## Possible workarounds

1. Not to use the layer and just initialize it in the dependency. This is not a viable option for us since the epsagon instance should be initialized at the beginning, wrapped around the lambda and then shared the instance across al the service and that adds a lot of issues in dependency injection and so on.
2. A hack to require epsagon from the dependencies only if epsagon is available as a package and not having it as a dependency in the logger.
3. Initialize it twice (but I don't know what the consequences of this may be).

## Ideal solution

Any import of epsagon would share the same initialization parameters and whether you are using a layer or the package you could use it indistinctively

**Comment by arbiv** [comment]
Hi,

Epsagon reached its end-of-life, and we are not adding new functionality. As an alternative, I suggest considering AppDynamics for application monitoring and tracing. I can help connect you with relevant peers or provide additional resources to assist you in your evaluation.
