### ISSUE TITLE
Does epsagon node Lambda layer support latest nodejs v18 runtime?

### ISSUE THREAD

**Issue by lintaonz** [epsagon/epsagon-node#619]
I switch my Lambda from v16 to v18 runtime. It seems Epsagon auto-tracing not working anymore.

Does the Epsagon node Lambda layer support the latest nodejs v18 runtime?

Cheers,

**Comment by arbiv** [comment]
Hi,

Epsagon reached its end-of-life, and we are not adding new functionality. As an alternative, I suggest considering AppDynamics for application monitoring and tracing. I can help connect you with relevant peers or provide additional resources to assist you in your evaluation.
