### ISSUE TITLE
Does Epsagon wrapper support async/await style of lambdas?

### ISSUE THREAD

**Issue by vitali-ausianik** [epsagon/epsagon-node#80]
Hello Guys!
Just a quick question for confirmation.
Lambda function with Node 8.10 runtime supports async/await style of coding. What about Epsagon?
Will code below work as expected?
```
const epsagon = require('epsagon');

const handler = async event => {
  try {
    // do something
    return result;
  } catch (err) {
    // do something
    throw err;
  }
}

epsagon.init({
  token: 'my-token',
  appName: 'my-app-name',
  metadataOnly: true, // or false
});

exports.handler = epsagon.lambdaWrapper(handler);
```

Thanks!

**Comment by ranrib** [comment]
Hi @vitali-ausianik - this will definitely work. Epsagon supports both async and non-async handler functions. Epsagon will wait until your function fully ends, and then it will send a trace. Let us know if you encounter any issue.

**Comment by vitali-ausianik** [comment]
Sorry for reopening, I have something to add for this topic. I'm trying to use epsagon v.1.19.0 (1.19.1 doesn't work - throws error every function execution)
My setup contains four functions using async/await style of coding. Every function uses separate application name for ```epsagon.init```. Unfortunately it doesn't send any trace messages to epsagon site. I see this "silence" issue only from AWS environment. In case if I try to execute these functions locally (for example using ```lambda-local``` package) - it works as expected and sends data to epsagon api (I can see it in my cabinet on epsagon site). 

Please help me to fix it. I'm not sure how to enable debug mode, so don't have any logs from epsagon package.

**Comment by ranrib** [comment]
Hi @vitali-ausianik can you please contact us via the help widget in the product? Thanks

**Comment by rehanvdm** [comment]
Hi, 

This is not working for me. If you try and await on that handler, it returns immeadtly. 
```
 let result = await app.handler(event);
```

Is there something that I am missing ? Is ```epsagon.lambdaWrapper``` async?
