### ISSUE TITLE
epsagon.lambdaWrapper is not async

### ISSUE THREAD

**Issue by rehanvdm** [epsagon/epsagon-node#82]
This post https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/ shows how to use async function properly. Here is what I am doing: 
```js
let AWS = require('aws-sdk');
let lambda = new AWS.Lambda();

exports.handler = async (event) => {
    return await lambda.getAccountSettings().promise() ;
};
```

Then I can test this file as:
```js
. . .
let result = await app.handler(event);
. . .
```
This works, it will wait for app.handler to finish before continuing with execution. BUT I can not do this with Epsagon, if I change the program as you suggest:
```js
let AWS = require('aws-sdk');
let lambda = new AWS.Lambda();
const epsagon = require('epsagon');

const handler = async event => {
  return await lambda.getAccountSettings().promise() ;
}

epsagon.init({
  token: 'my-token',
  appName: 'my-app-name',
  metadataOnly: true, // or false
});

exports.handler = epsagon.lambdaWrapper(handler);
```

This does not work, it does not await in the test, it returns immediately with a `undefined` and continues. This tells me that lambdaWrapper is not Async. Can you please make it async?

**Comment by ranrib** [comment]
Hi @rehanvdm , In this case you can just do like:
```
let AWS = require('aws-sdk');
let lambda = new AWS.Lambda();
const epsagon = require('epsagon');

epsagon.init({
  token: 'my-token',
  appName: 'my-app-name',
  metadataOnly: true, // or false
});


const handler = epsagon.lambdaWrapper(async event => {
  return await lambda.getAccountSettings().promise() ;
});
```

And it will work. Let me know if you encounter any issue (you can do that also via the help widget on the dashboard).

**Comment by ranrib** [comment]
Hi @rehanvdm, Epsagon `lambdaWrapper` returns the same value as the original function - in an Async function it will return a Promise, that will allow you to do await. the following code worked for me:

```
let AWS = require('aws-sdk');
let lambda = new AWS.Lambda();

const epsagon = require('epsagon');

epsagon.init({
  token: 'my-token',
  appName: 'my-app-name',
  metadataOnly: false
});

const handler = epsagon.lambdaWrapper(async (event) => {
    return await lambda.getAccountSettings().promise();
});

const test = async () => {
    console.log(await handler('test'))
};

test()
```

By the way, you may consider discarding the await in the handler:
```
const handler = async event => {
  return lambda.getAccountSettings().promise() ;
}
````

**Comment by rehanvdm** [comment]
Okay I think I found the problem. It is when ever I pass in both event and context params to the lambda. 

So can you please confirm that this fails for you as well? 

```js
let AWS = require('aws-sdk');
let lambda = new AWS.Lambda();

const epsagon = require('epsagon');

epsagon.init({
  token: 'my-token',
  appName: 'my-app-name',
  metadataOnly: false
});

const handler = epsagon.lambdaWrapper(async (event,context) => {
    return await lambda.getAccountSettings().promise();
});

const test = async () => {
    let context = {};
    console.log(await handler('test',context ));
};

test()
```

**Comment by ranrib** [comment]
In such case - you won't see a trace in Epsagon - since this is not a valid Lambda context (in case the wrapper detect something unfamiliar, it just drops the trace).
Your code should still be able to run as usual.
I tested on my end and got a valid response:
`
let AWS = require('aws-sdk');
AWS.config.update({region:'us-east-1'});
const epsagon = require('epsagon');
let lambda = new AWS.Lambda();

const handler = epsagon.lambdaWrapper(async (event, context) => {
    return await lambda.getAccountSettings().promise();
});

const test = async () => {
    let context = {};
    console.log(await handler('test'), context)
};

test()
`
output:
```
{ AccountLimit: 
   { TotalCodeSize: ---,
     CodeSizeUnzipped: ---,
     CodeSizeZipped: ---,
     ConcurrentExecutions: ---,
     UnreservedConcurrentExecutions: -- },
  AccountUsage: { TotalCodeSize: --, FunctionCount: -- } } {}
```

**Comment by ranrib** [comment]
In such case - you are right - Epsagon expects to get a valid context as an input, if given.

**Comment by rehanvdm** [comment]
Okay, according to https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html, there are quite a few properties. I only make use of one or 2 in my code. So for local testing, I don't know all those values and I assume that if I fill them in wrong Epsagon when sending the trace or when analyzing it will throw an error somewhere along the line ?

What do you suggest I do for local testing?

**Comment by ranrib** [comment]
for local testing you can set DISABLE_EPSAGON = TRUE (environment variable), it will disable all Epsagon wrappers.

**Comment by rehanvdm** [comment]
If I set this above epsagon init and the wrapper, it works. Thank you
```js
process.env.DISABLE_EPSAGON = true;
```

**Comment by rehanvdm** [comment]
Confirmed, testing locally, I set that above the test, then when deployed to AWS it works as expected and traces get send
